language: python
sudo: false
matrix:
  include:
    - env: TOXENV=py27-1.4.x
      python: 2.7
    - env: TOXENV=py27-1.5.x
      python: 2.7
    - env: TOXENV=py27-1.6.x
      python: 2.7
    - env: TOXENV=py27-1.7.x
      python: 2.7
    - env: TOXENV=py27-1.8.x
      python: 2.7
    - env: TOXENV=py27-1.9.x
      python: 2.7
    - env: TOXENV=py33-1.5.x
      python: 3.3
    - env: TOXENV=py33-1.6.x
      python: 3.3
    - env: TOXENV=py33-1.7.x
      python: 3.3
    - env: TOXENV=py33-1.8.x
      python: 3.3
    - env: TOXENV=py34-1.5.x
      python: 3.4
    - env: TOXENV=py34-1.6.x
      python: 3.4
    - env: TOXENV=py34-1.7.x
      python: 3.4
    - env: TOXENV=py34-1.8.x
      python: 3.4
    - env: TOXENV=py34-1.9.x
      python: 3.4
    - env: TOXENV=py35-1.8.x
      python: 3.5
    - env: TOXENV=py35-1.9.x
      python: 3.5

install:
  - pip install flake8 tox isort

before_script:
  - flake8 taggit
  - python setup.py isort

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov -e TOX_ENV TRAVIS_OS_NAME

notifications:
  email: false
