language: python
sudo: false
matrix:
  include:
    - env: TOXENV=py27-1.8.x
      python: 2.7
    - env: TOXENV=py27-1.9.x
      python: 2.7
    - env: TOXENV=py27-1.10.x
      python: 2.7
    - env: TOXENV=py33-1.8.x
      python: 3.3
    - env: TOXENV=py34-1.8.x
      python: 3.4
    - env: TOXENV=py34-1.9.x
      python: 3.4
    - env: TOXENV=py34-1.10.x
      python: 3.4
    - env: TOXENV=py35-1.8.x
      python: 3.5
    - env: TOXENV=py35-1.9.x
      python: 3.5
    - env: TOXENV=py35-1.10.x
      python: 3.5

install:
  - pip install flake8 tox isort

before_script:
  - flake8 taggit
  - python setup.py isort

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov -e TOXENV CI TRAVIS_BUILD_ID TRAVIS TRAVIS_BRANCH TRAVIS_JOB_NUMBER TRAVIS_PULL_REQUEST TRAVIS_JOB_ID TRAVIS_REPO_SLUG TRAVIS_COMMIT

notifications:
  email: false
